sudo: false
language: c
stages:
  - install
  - analyze
  - build
  - test
jobs:
  include:
    - stage: install
      script: brew install cppcheck
      if: os = macos
    - stage: analzye
      script: s/cppcheck
    - stage: build
      script: s/build
    - stage: test
      script: build/atl-cli help
  exclude:
    - os: macos
      stage: analyze
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
#  homebrew:
#    packages:
#      - cppcheck
#    update: yes
script:
  - s/cppcheck
  - s/build
os:
  - linux
  - macos
