sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  homebrew:
    packages:
      - cppcheck
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
    update: true
script:
  - s/cppcheck
  - s/build
os:
  - linux
  - macos
