sudo: false
language: c
stages: 
  - check
  - test
jobs:
  include:
    - os: macos
      stage: check
      install: brew install cppcheck
    - stage: check
      script: s/cppcheck
    - stage: test
      script: 
        - s/build
        - build/atl-cli help
  exclude:
    - os: macos
      stage: check
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
os:
  - linux
  - macos
