sudo: false
language: c
stages: 
  - check
  - build
  - test
jobs:
  include:
    - stage: check
      script: s/cppcheck
    - stage: build
      script: s/build
  exclude:
    - os: osx
      stage: check
compiler:
  - gcc
  - clang
script:
  - build/atl-cli
addons:
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
os:
  - linux
  - osx
dist: bionic

