sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  homebrew:
    packages:
      - cppcheck
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
os:
  - linux
  - macos
