sudo: false
language: c
jobs:
  include:
    - stage: install
      script: which cppcheck
      if: os = macos
    - stage: analzye
      script: s/cppcheck
    - stage: build
      script: s/build
    - stage: test
      script: build/atl-cli help
  exclude:
    - os: macos
      stage: analyze
compiler:
  - gcc
  - clang
addons:
  homebrew:
    packages:
      - cppcheck
    update: true
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
script:
  - s/cppcheck
  - s/build
os:
  - linux
  - macos
