sudo: false
language: c
stages: 
  - analyze
  - build
jobs:
  include:
    - os: macos
      stage: analyze
      install: brew install cppcheck
    - stage: analyze
      script: s/cppcheck
    - stage: build
      script: 
        - s/build
        - build/atl-cli help
  exclude:
    - os: macos
      stage: analyze
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
os:
  - linux
  - macos
