sudo: false
language: c
stages: 
  - check
  - test
jobs:
  include:
    - stage: check
      script: s/cppcheck
  exclude:
    - os: osx
      stage: check
compiler:
  - gcc
  - clang
script:
  - s/build
  - build/atl-cli
addons:
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
os:
  - linux
  - osx
