sudo: false
language: c
stages: 
  - check
  - test
jobs:
  include:
    - os: osx
      stage: check
      install: brew install cppcheck
    - stage: check
      script: s/cppcheck
    - stage: test
      script: build/atl-cli help
  exclude:
    - os: osx
      stage: check
compiler:
  - gcc
  - clang
script: 
  - s/build
addons:
  apt:
    packages:
      - libbsd-dev
      - libsqlite3-dev
      - cppcheck
os:
  - linux
  - osx
