#!/bin/sh
IGNORE=$(find . -name "*.test.c" | awk '{ print "-i"$1 }')

cppcheck --force --quiet --enable=warning,performance,portability \
 $IGNORE -icJSON -iclibs \
 -USTBDS_NO_SHORT_NAMES -USTBDS_UNIT_TESTS \
 -U_MSC_VER -UCLEANUP_CODE -UTODO \
 -UERESSEA_BUILDNO -UERESSEA_VERSION -UTEST_THREADS \
 .
